version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: bychat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: bychat_redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: bychat_nginx
    ports:
       - "161.132.45.210:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: unless-stopped

  web:
    build: .
    container_name: bychat_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: # <--- AQUÍ ESTÁ LA SECCIÓN AÑADIDA
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  worker:
    build: .
    container_name: bychat_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: unless-stopped

volumes:
  postgres_data: